/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AppImport } from './routes/app'
import { Route as IndexImport } from './routes/index'
import { Route as AppIndexImport } from './routes/app/index'
import { Route as AppCreateImport } from './routes/app/create'
import { Route as AppDominionDominionIdImport } from './routes/app/dominion/$dominionId'

// Create/Update Routes

const AppRoute = AppImport.update({
  path: '/app',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const AppIndexRoute = AppIndexImport.update({
  path: '/',
  getParentRoute: () => AppRoute,
} as any)

const AppCreateRoute = AppCreateImport.update({
  path: '/create',
  getParentRoute: () => AppRoute,
} as any)

const AppDominionDominionIdRoute = AppDominionDominionIdImport.update({
  path: '/dominion/$dominionId',
  getParentRoute: () => AppRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/app': {
      preLoaderRoute: typeof AppImport
      parentRoute: typeof rootRoute
    }
    '/app/create': {
      preLoaderRoute: typeof AppCreateImport
      parentRoute: typeof AppImport
    }
    '/app/': {
      preLoaderRoute: typeof AppIndexImport
      parentRoute: typeof AppImport
    }
    '/app/dominion/$dominionId': {
      preLoaderRoute: typeof AppDominionDominionIdImport
      parentRoute: typeof AppImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexRoute,
  AppRoute.addChildren([
    AppCreateRoute,
    AppIndexRoute,
    AppDominionDominionIdRoute,
  ]),
])

/* prettier-ignore-end */
